---
abstract: 'Tags helper for login request.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  CSS::Struct::Output::Structure: 0
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Tags::Output::Structure: 0
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-HTML-Login-Request
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Error::Pure: 0
  List::Util: 1.33
  Mo::utils::CSS: 0.07
  Mo::utils::Language: 0.05
  Readonly: 0
  Tags::HTML: 0
  Tags::HTML::Messages: 0.09
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Tags-HTML-Login-Request/issues
  homepage: https://github.com/michal-josef-spacek/Tags-HTML-Login-Request
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-HTML-Login-Request
version: '0.03'
